language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - { python: 3.5, env: TOXENV=docs }
    - { python: 3.5, env: TOXENV=lint }
install:
  - pip install tox-travis
script:
  - tox
